### PR TITLE
feat: Module export make consistent between multiple bundles

### PR DESCRIPTION
**Pull request by delagen**
Upgrade dependencies. 
Make ES2015 and generic module export object {defaults,utils,CacheFactory,Cache}

### CODE REVIEW

**Comment by delagen** [comment]
@jmdobry any news?

**Comment by delagen** [comment]
@jmdobry anybody here?

**Review by jmdobry — APPROVED** [review]
I'm merging, then I'll do some cleanup.

**Comment by delagen** [comment]
Please publish NPM also. Thanks for merge

**Comment by jmdobry** [comment]
Done

**Pull request merged**
