### PR TITLE
feat: TS provide consistent typescript definition

### PR DESCRIPTION
**Pull request by delagen**
For example valid TS code
```ts
import * as CacheFactory from "cachefactory";
const cache:CacheFactory.Cache = new CacheFactory.Cache();
```

### CODE REVIEW

**Comment by delagen** [comment]
@jmdobry please merge it

**Comment by fracz** [comment]
Thank you for these typings! One suggestion - wouldn't it be better to be declared as a module?  `import {CacheFactory} from "cachefactory"` would make more sense to me.

**Comment by delagen** [comment]
@fracz It can be rewritten easy, but for this module must be bundled the same
For current it exports directly constructor for commonjs and if you choose es2015 it will be default export ie
```
import CacheFactory from "cachefactory"
```
which also not recommended

**Comment by delagen** [comment]
@fracz made #29 that override this in favour of consistent export
@jmdobry consider this when merge

**Comment by jmdobry** [comment]
So close #28 in favor of #29?

**Comment by delagen** [comment]
@jmdobry I agree with both. But in case of consistensy preferred #29
PS. Also please notice that it can broke dependent code.

**Comment by jmdobry** [comment]
Closing in favor of #29

**Pull request closed without merging**
